package com.github.pires.obd.reader.io

import android.content.Context
import android.os.Environment
import android.util.Log
import com.github.pires.obd.reader.net.ObdReading
import java.io.*

class LogCSVWriter(filename: String, dirname: String, context: Context) {

    private var isFirstLine: Boolean = true
    private var buf: BufferedWriter? = null

    init {
        try {
            val dir = File(context.getExternalFilesDir(null), dirname)
            if (!dir.exists()) dir.mkdirs()
            Log.d(TAG, "Path is ${dir.absolutePath}")
            val file = File(dir, filename)
            val fos = FileOutputStream(file)
            val osw = OutputStreamWriter(fos)
            this.buf = BufferedWriter(osw)
            this.isFirstLine = true
            Log.d(TAG, "Constructed the LogCSVWriter")
        } catch (e: Exception) {
            Log.e(TAG, "LogCSVWriter constructor failed", e)
        }
    }

    fun closeLogCSVWriter() {
        try {
            buf?.flush()
            buf?.close()
            Log.d(TAG, "Flushed and closed")
        } catch (e: IOException) {
            e.printStackTrace()
        }
    }

    fun writeLineCSV(reading: ObdReading) {
        if (buf == null) return

        var crl: String
        if (isFirstLine) {
            crl = HEADER_CSV + reading.toString()
            addLine(crl)
            isFirstLine = false

            // Add line with the columns
            val sb = StringBuilder()
            for (ccln in NAMES_COLUMNS) {
                sb.append(ccln).append(";")
            }
            addLine(sb.substring(0, sb.length - 1)) // remove last ";"
        } else {
            val sb = StringBuilder()
            sb.append(reading.timestamp).append(";")
                .append(reading.latitude).append(";")
                .append(reading.longitude).append(";")
                .append(reading.altitude).append(";")
                .append(reading.vin).append(";")

            val read = reading.readings
            for (ccln in NAMES_COLUMNS_ONLY_READINGS) {
                sb.append(read[ccln]).append(";")
            }
            addLine(sb.substring(0, sb.length - 1))
        }
    }

    private fun addLine(line: String?) {
        if (line != null) {
            try {
                buf?.write(line, 0, line.length)
                buf?.newLine()
                Log.d(TAG, "LogCSVWriter: Wrote $line")
            } catch (e: IOException) {
                e.printStackTrace()
            }
        }
    }

    companion object {
        private val TAG = LogCSVWriter::class.java.name
        private const val HEADER_CSV = "This is a logfile generated by pires.obd.reader"
        private val NAMES_COLUMNS = arrayOf(
            "TIME", "LATITUDE", "LONGITUDE", "ALTITUDE", "VEHICLE_ID",
            "BAROMETRIC_PRESSURE", "ENGINE_COOLANT_TEMP", "FUEL_LEVEL", "ENGINE_LOAD", "AMBIENT_AIR_TEMP",
            "ENGINE_RPM", "INTAKE_MANIFOLD_PRESSURE", "MAF", "Term Fuel Trim Bank 1",
            "FUEL_ECONOMY", "Long Term Fuel Trim Bank 2", "FUEL_TYPE", "AIR_INTAKE_TEMP",
            "FUEL_PRESSURE", "SPEED", "Short Term Fuel Trim Bank 2",
            "Short Term Fuel Trim Bank 1", "ENGINE_RUNTIME", "THROTTLE_POS", "DTC_NUMBER",
            "TROUBLE_CODES", "TIMING_ADVANCE", "EQUIV_RATIO"
        )
        private val NAMES_COLUMNS_ONLY_READINGS = arrayOf(
            "BAROMETRIC_PRESSURE", "ENGINE_COOLANT_TEMP", "FUEL_LEVEL", "ENGINE_LOAD", "AMBIENT_AIR_TEMP",
            "ENGINE_RPM", "INTAKE_MANIFOLD_PRESSURE", "MAF", "Term Fuel Trim Bank 1",
            "FUEL_ECONOMY", "Long Term Fuel Trim Bank 2", "FUEL_TYPE", "AIR_INTAKE_TEMP",
            "FUEL_PRESSURE", "SPEED", "Short Term Fuel Trim Bank 2",
            "Short Term Fuel Trim Bank 1", "ENGINE_RUNTIME", "THROTTLE_POS", "DTC_NUMBER",
            "TROUBLE_CODES", "TIMING_ADVANCE", "EQUIV_RATIO"
        )
    }
}
